### ISSUE TITLE
Paganini does not list cvxopt as a requirement

### ISSUE THREAD

**Issue by maciej-bendkowski** [maciej-bendkowski/boltzmann-brain#3]
Neither in the README nor in the help message does paganini list _cvxopt_ as a requirement.

**Comment by maciej-bendkowski** [comment]
After reflection I decided that the issue is more of a user experience bug than a necessary enhancement.

**Comment by Sergey-A-Dovgal** [comment]
There is no bug: we don't use cvxopt package. Instead we use cvxpy, and during the launch, this package is listed if missing.

**Comment by Sergey-A-Dovgal** [comment]
The only bug is the old comment line "cvxopt is truly necessary" which is obsolete ;)

**Comment by maciej-bendkowski** [comment]
@Electric-tric -- correct. However, the current version does require cvxopt to run. The dependency should be removed.

**Comment by Sergey-A-Dovgal** [comment]
You are right - fixed.
