### ISSUE TITLE
Upgrade haskell-src-exts version

### ISSUE THREAD

**Issue by maciej-bendkowski** [maciej-bendkowski/boltzmann-brain#6]
_Boltzmann brain_ should support with newest _ghc_. In particular, compiler crafting utilities should be adjusted to the new changes in _haskell-src-exts_.

**Comment by maciej-bendkowski** [comment]
Commit e6f24aca88a14d02871b8acd42613af541e7cee9 switches to the lts-9.1 stack resolver. With that, the default ghc version becomes 8.0.2. Nonetheless, `haskell-src-exts-1.17.1` is still a hard dependency.

**Comment by timsears** [comment]
@maciej-bendkowski Just fyi, I started working on this in my fork, in the updates branch. Now compiles with ghc 8.65 and haskell-src-exts-1.21.1 

Planning to add nix support before making a pull request.

**Comment by timsears** [comment]
see #16

**Comment by maciej-bendkowski** [comment]
Thanks, Tim! Your changes were merged.
